### ISSUE TITLE
panic in the usage of plugin

### ISSUE THREAD

**Issue by dberardo-com** [tomMoulard/fail2ban#114]
i get this error

```
time="2024-05-16T09:31:57Z" level=error msg="Stack: goroutine 731 [running]:\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x7efe049dbcd8, 0xc001c2c068}, 0xc000d01300)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:46 +0x225\npanic({0x3a23a40, 0xc00130ea00})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/yaegi/interp.runCfg.func1()\n\tgithub.com/traefik/yaegi@v0.14.3/interp/run.go:192 +0x148\npanic({0x3a23a40, 0xc00130ea00})\n\truntime/panic.go:884 +0x212\nreflect.Value.call({0x3aeac20?, 0xc00189b2c0?, 0x41057f?}, {0x47005d6, 0x4}, {0xc0013f8588, 0x1, 0x0?})\n\treflect/value.go:440 +0x1abf\nreflect.Value.Call({0x3aeac20?, 0xc00189b2c0?, 0x455292?}, {0xc0013f8588?, 0x469cee0?, 0x1?})\n\treflect/value.go:368 +0xbc\ngithub.com/traefik/yaegi/interp.call.func9.2({0xc0013f8588?, 0xc00189b2c0?, 0x5?})\n\tgithub.com/traefik/yaegi@v0.14.3/interp/run.go:1288 +0x3c\ngithub.com/traefik/yaegi/interp.call.func9(0xc0011222c0)\n\tgithub.com/traefik/yaegi@v0.14.3/interp/run.go:1303 +0x122f\ngithub.com/traefik/yaegi/interp.runCfg(0xc0015a58c0, 0xc0011222c0, 0x0?, 0x4589940?)\n\tgithub.com/traefik/yaegi@v0.14.3/interp/run.go:200 +0x29d\ngithub.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc00189b170, 0x2, 0x4?})\n\tgithub.com/traefik/yaegi@v0.14.3/interp/run.go:1002 +0x4a5\ngithub.com/traefik/yaegi/stdlib._net_http_Handler.ServeHTTP(...)\n\tgithub.com/traefik/yaegi@v0.14.3/stdlib/go1_19_net_http.go:290\ngithub.com/traefik/traefik/v2/pkg/middlewares/headers.(*Header).ServeHTTP(0xc001aa9fc0, {0x7efe049dbcd8?, 0xc001c2c068}, 0xc000d01400)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/headers/header.go:64 +0x15d\ngithub.com/traefik/traefik/v2/pkg/middlewares/connectionheader.Remover.func1({0x7efe049dbcd8, 0xc001c2c068}, 0xc000d01400)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/connectionheader/connectionheader.go:34 +0x279\nnet/http.HandlerFunc.ServeHTTP(0x3493807?, {0x7efe049dbcd8?, 0xc001c2c068?}, 0x5269810?)\n\tnet/http/server.go:2109 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares/headers.(*headers).ServeHTTP(0x52bfbb0?, {0x7efe049dbcd8?, 0xc001c2c068?}, 0x5270640?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/headers/headers.go:91 +0x2c\ngithub.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc001ad5c50, {0x7efe049dbcd8, 0xc001c2c068}, 0xc000d01400)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/tracing/wrapper.go:57 +0x106\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc001ae2000, {0x7efe049dbcd8, 0xc001c2c068}, 0x3c35a80?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:31 +0x122\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0019c6de0, {0x7efe049dbcd8, 0xc001c2c068}, 0xc000d01300)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:141 +0x24c\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0x7dfaea0?, {0x7efe049dbcd8?, 0xc001c2c068?}, 0x3a1d640?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:32 +0x82\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc001ae21c0, {0x7efe049dbcd8, 0xc001c2c068}, 0xc000e5d0e0?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:31 +0x122\ngithub.com/traefik/traefik/v2/pkg/middlewares/metrics.(*metricsMiddleware).ServeHTTP(0xc001accd80, {0x7efe049dbcd8?, 0xc001c2c068}, 0xc000d01300)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/metrics/metrics.go:146 +0x788\ngithub.com/traefik/traefik/v2/pkg/middlewares/capture.Wrap.func1({0x52b3450, 0xc001c2c060}, 0xc001b56dbd?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/capture/capture.go:48 +0x7e\nnet/http.HandlerFunc.ServeHTTP(0xc000efe340?, {0x52b3450?, 0xc001c2c060?}, 0xc00140a400?)\n\tnet/http/server.go:2109 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares/snicheck.SNICheck.ServeHTTP({{0x529b220?, 0xc001b00048?}, 0xc001b15d70?}, {0x52b3450, 0xc001c2c060}, 0xc000d01100)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/snicheck/snicheck.go:49 +0x189\ngithub.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0x4108c7?, {0x52b3450, 0xc001c2c060}, 0x5270701?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/handler_switcher.go:23 +0x62\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc000013df0, {0x52b3450, 0xc001c2c060}, 0xc000d01000, 0xc000bf4b80)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x30e\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x52b3450?, 0xc001c2c060?}, 0xc00189af90?)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:89 +0x68\nnet/http.HandlerFunc.ServeHTTP(0xc000d05d60?, {0x52b3450?, 0xc001c2c060?}, 0x9?)\n\tnet/http/server.go:2109 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc000d05d60, {0x52b3450, 0xc001c2c060}, 0xc000d01000)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders/forwarded_header.go:192 +0xca\nnet/http.AllowQuerySemicolons.func1({0x52b3450, 0xc001c2c060}, 0xc000d01000)\n\tnet/http/server.go:2974 +0x223\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x52b3450?, 0xc001c2c060?}, 0xc00141fb80?)\n\tnet/http/server.go:2109 +0x2f\nnet/http.serverHandler.ServeHTTP({0x280?}, {0x52b3450, 0xc001c2c060}, 0xc000d01000)\n\tnet/http/server.go:2947 +0x30c\nnet/http.initALPNRequest.ServeHTTP({{0x52bfbb0?, 0xc0016520f0?}, 0xc001cd4380?, {0xc000fb8870?}}, {0x52b3450, 0xc001c2c060}, 0xc000d01000)\n\tnet/http/server.go:3556 +0x245\ngolang.org/x/net/http2.(*serverConn).runHandler(0x52ad438?, 0x7e2de50?, 0x0?, 0x0?)\n\tgolang.org/x/net@v0.3.1-0.20221206200815-1e63c2f08a10/http2/server.go:2305 +0x83\ncreated by golang.org/x/net/http2.(*serverConn).processHeaders\n\tgolang.org/x/net@v0.3.1-0.20221206200815-1e63c2f08a10/http2/server.go:2018 +0x64a\n" middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2024-05-16T09:31:57Z" level=error msg="plugins-storage/sources/gop-714367021/src/github.com/tomMoulard/fail2ban/fail2ban.go:218:2: panic" plugin=plugin-fail2ban module=github.com/tomMoulard/fail2ban
```

<details><summary>With proper formating</summary>
<p>

```
time="2024-05-16T09:31:57Z" level=error msg="Stack: goroutine 731 [running]:
github.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x7efe049dbcd8, 0xc001c2c068}, 0xc000d01300)
	github.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:46 +0x225
panic({0x3a23a40, 0xc00130ea00})
	runtime/panic.go:884 +0x212
github.com/traefik/yaegi/interp.runCfg.func1()
	github.com/traefik/yaegi@v0.14.3/interp/run.go:192 +0x148
panic({0x3a23a40, 0xc00130ea00})
	runtime/panic.go:884 +0x212
reflect.Value.call({0x3aeac20?, 0xc00189b2c0?, 0x41057f?}, {0x47005d6, 0x4}, {0xc0013f8588, 0x1, 0x0?})
	reflect/value.go:440 +0x1abf
reflect.Value.Call({0x3aeac20?, 0xc00189b2c0?, 0x455292?}, {0xc0013f8588?, 0x469cee0?, 0x1?})
	reflect/value.go:368 +0xbc
github.com/traefik/yaegi/interp.call.func9.2({0xc0013f8588?, 0xc00189b2c0?, 0x5?})
	github.com/traefik/yaegi@v0.14.3/interp/run.go:1288 +0x3c
github.com/traefik/yaegi/interp.call.func9(0xc0011222c0)
	github.com/traefik/yaegi@v0.14.3/interp/run.go:1303 +0x122f
github.com/traefik/yaegi/interp.runCfg(0xc0015a58c0, 0xc0011222c0, 0x0?, 0x4589940?)
	github.com/traefik/yaegi@v0.14.3/interp/run.go:200 +0x29d
github.com/traefik/yaegi/interp.genFunctionWrapper.func1.1({0xc00189b170, 0x2, 0x4?})
	github.com/traefik/yaegi@v0.14.3/interp/run.go:1002 +0x4a5
github.com/traefik/yaegi/stdlib._net_http_Handler.ServeHTTP(...)
	github.com/traefik/yaegi@v0.14.3/stdlib/go1_19_net_http.go:290
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*Header).ServeHTTP(0xc001aa9fc0, {0x7efe049dbcd8?, 0xc001c2c068}, 0xc000d01400)
	github.com/traefik/traefik/v2/pkg/middlewares/headers/header.go:64 +0x15d
github.com/traefik/traefik/v2/pkg/middlewares/connectionheader.Remover.func1({0x7efe049dbcd8, 0xc001c2c068}, 0xc000d01400)
	github.com/traefik/traefik/v2/pkg/middlewares/connectionheader/connectionheader.go:34 +0x279
net/http.HandlerFunc.ServeHTTP(0x3493807?, {0x7efe049dbcd8?, 0xc001c2c068?}, 0x5269810?)
	net/http/server.go:2109 +0x2f
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*headers).ServeHTTP(0x52bfbb0?, {0x7efe049dbcd8?, 0xc001c2c068?}, 0x5270640?)
	github.com/traefik/traefik/v2/pkg/middlewares/headers/headers.go:91 +0x2c
github.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc001ad5c50, {0x7efe049dbcd8, 0xc001c2c068}, 0xc000d01400)
	github.com/traefik/traefik/v2/pkg/middlewares/tracing/wrapper.go:57 +0x106
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc001ae2000, {0x7efe049dbcd8, 0xc001c2c068}, 0x3c35a80?)
	github.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:31 +0x122
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0019c6de0, {0x7efe049dbcd8, 0xc001c2c068}, 0xc000d01300)
	github.com/gorilla/mux@v1.8.0/mux.go:141 +0x24c
github.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0x7dfaea0?, {0x7efe049dbcd8?, 0xc001c2c068?}, 0x3a1d640?)
	github.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:32 +0x82
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc001ae21c0, {0x7efe049dbcd8, 0xc001c2c068}, 0xc000e5d0e0?)
	github.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:31 +0x122
github.com/traefik/traefik/v2/pkg/middlewares/metrics.(*metricsMiddleware).ServeHTTP(0xc001accd80, {0x7efe049dbcd8?, 0xc001c2c068}, 0xc000d01300)
	github.com/traefik/traefik/v2/pkg/middlewares/metrics/metrics.go:146 +0x788
github.com/traefik/traefik/v2/pkg/middlewares/capture.Wrap.func1({0x52b3450, 0xc001c2c060}, 0xc001b56dbd?)
	github.com/traefik/traefik/v2/pkg/middlewares/capture/capture.go:48 +0x7e
net/http.HandlerFunc.ServeHTTP(0xc000efe340?, {0x52b3450?, 0xc001c2c060?}, 0xc00140a400?)
	net/http/server.go:2109 +0x2f
github.com/traefik/traefik/v2/pkg/middlewares/snicheck.SNICheck.ServeHTTP({{0x529b220?, 0xc001b00048?}, 0xc001b15d70?}, {0x52b3450, 0xc001c2c060}, 0xc000d01100)
	github.com/traefik/traefik/v2/pkg/middlewares/snicheck/snicheck.go:49 +0x189
github.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0x4108c7?, {0x52b3450, 0xc001c2c060}, 0x5270701?)
	github.com/traefik/traefik/v2/pkg/middlewares/handler_switcher.go:23 +0x62
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc000013df0, {0x52b3450, 0xc001c2c060}, 0xc000d01000, 0xc000bf4b80)
	github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x30e
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x52b3450?, 0xc001c2c060?}, 0xc00189af90?)
	github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:89 +0x68
net/http.HandlerFunc.ServeHTTP(0xc000d05d60?, {0x52b3450?, 0xc001c2c060?}, 0x9?)
	net/http/server.go:2109 +0x2f
github.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc000d05d60, {0x52b3450, 0xc001c2c060}, 0xc000d01000)
	github.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders/forwarded_header.go:192 +0xca
net/http.AllowQuerySemicolons.func1({0x52b3450, 0xc001c2c060}, 0xc000d01000)
	net/http/server.go:2974 +0x223
net/http.HandlerFunc.ServeHTTP(0x0?, {0x52b3450?, 0xc001c2c060?}, 0xc00141fb80?)
	net/http/server.go:2109 +0x2f
net/http.serverHandler.ServeHTTP({0x280?}, {0x52b3450, 0xc001c2c060}, 0xc000d01000)
	net/http/server.go:2947 +0x30c
net/http.initALPNRequest.ServeHTTP({{0x52bfbb0?, 0xc0016520f0?}, 0xc001cd4380?, {0xc000fb8870?}}, {0x52b3450, 0xc001c2c060}, 0xc000d01000)
	net/http/server.go:3556 +0x245
golang.org/x/net/http2.(*serverConn).runHandler(0x52ad438?, 0x7e2de50?, 0x0?, 0x0?)
	golang.org/x/net@v0.3.1-0.20221206200815-1e63c2f08a10/http2/server.go:2305 +0x83
created by golang.org/x/net/http2.(*serverConn).processHeaders
	golang.org/x/net@v0.3.1-0.20221206200815-1e63c2f08a10/http2/server.go:2018 +0x64a
" middlewareName=traefik-internal-recovery middlewareType=Recovery

```

</p>
</details>

**Comment by dberardo-com** [comment]
rolling back to v 0.6.6 of the plugin on traefik 2.9.6 fixes the error

**Comment by tomMoulard** [comment]
Hello @dberardo-com,

Thanks for your interest in this Traefik plugin !

Can you give a reproducible use case ?
